version: '2'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_DATABASE: airflow
      POSTGRESQL_USERNAME: airflow
      POSTGRESQL_PASSWORD: airflow
      ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 5432:5432


  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      ALLOW_EMPTY_PASSWORD: "true"

  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2.1.0
    environment:
      AIRFLOW_DATABASE_NAME: airflow
      AIRFLOW_DATABASE_USERNAME: airflow
      AIRFLOW_DATABASE_PASSWORD: airflow
      AIRFLOW_EXECUTOR: CeleryExecutor
      AIRFLOW_WEBSERVER_HOST: airflow
      AIRFLOW_LOAD_EXAMPLES: "false"
      AIRFLOW_FERNET_KEY: 8GX5ReVf41G2dSFBpjIXnuEkSjaFyGpNW8VqV3qiBY8=
    volumes:
      - ./src/dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins/git_ais


  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2.1.0
    environment:
      AIRFLOW_DATABASE_NAME: airflow
      AIRFLOW_DATABASE_USERNAME: airflow
      AIRFLOW_DATABASE_PASSWORD: airflow
      AIRFLOW_EXECUTOR: CeleryExecutor
      AIRFLOW_WEBSERVER_HOST: airflow
      AIRFLOW_LOAD_EXAMPLES: "false"
      AIRFLOW_FERNET_KEY: 8GX5ReVf41G2dSFBpjIXnuEkSjaFyGpNW8VqV3qiBY8=
      AIRFLOW__SMTP__SMTP_SSL: "true"
      AIRFLOW__SMTP__SMTP_STARTTLS: "false"
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: ${SMTP_HOST}
      AIRFLOW__SMTP__SMTP_USER: ${SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${SMTP_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SMTP_MAIL_FROM}
      AIRFLOW__SMTP__SMTP_PORT: ${SMTP_PORT}
    volumes:
      - ./src/dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins/git_ais


  airflow:
    image: docker.io/bitnami/airflow:2.1.0
    depends_on:
      - postgresql
      - redis
      - airflow-scheduler
      - airflow-worker
    environment:
      AIRFLOW_DATABASE_NAME: airflow
      AIRFLOW_DATABASE_USERNAME: airflow
      AIRFLOW_DATABASE_PASSWORD: airflow
      AIRFLOW_EXECUTOR: CeleryExecutor
      AIRFLOW_LOAD_EXAMPLES: "false"
      AIRFLOW_FERNET_KEY: 8GX5ReVf41G2dSFBpjIXnuEkSjaFyGpNW8VqV3qiBY8=
      AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG
    ports:
      - '8080:8080'
    volumes:
      - ./src/dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins/git_ais

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

